/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <sdktools>
#include <sdkhooks>

public Plugin:myinfo = 
{
	name = "New Plugin",
	author = "Unknown",
	description = "<- Description ->",
	version = "1.0",
	url = "<- URL ->"
}

public OnClientPutInServer(client)
{
	SDKHook(client, SDKHook_OnTakeDamage, onTakeDamage);
}

public OnPluginStart()
{
	
}

public Action:onTakeDamage(victim, &attacker, &inflictor, &Float:damage, &damagetype, &weapon, Float:damageForce[3], Float:damagePosition[3])
{
	if (damage == 0.0)
		return Plugin_Continue;
	else
		if ((attacker > 0) && (attacker <= 32))
			PrintToChatAll("[%f] %f Damage", GetEngineTime(), damage);
	return Plugin_Continue;
}