/* Plugin Template generated by Pawn Studio */

#include <sourcemod>

public Plugin:myinfo = 
{
	name = "Death Test",
	author = "Unknown",
	description = "<- Description ->",
	version = "1.0",
	url = "<- URL ->"
}

public OnPluginStart()
{
	HookEvent("player_death", playerDeath, EventHookMode_Pre);
}

public Action:playerDeath(Handle:event, const String:name[], bool:dontBroadcast)
{
	PrintToChatAll("%d", GetEventInt(event, "userid"));
	return Plugin_Continue;
}