/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <sdktools>

public Plugin:myinfo = 
{
	name = "New Plugin",
	author = "Unknown",
	description = "<- Description ->",
	version = "1.0",
	url = "<- URL ->"
}

public OnPluginStart()
{
	RegAdminCmd("sm_teleport_all", TeleportAll, ADMFLAG_RCON);
}

public Action:TeleportAll(client, args)
{
	new String:arg1[15], String:arg2[15], String:arg3[15];
	
	GetCmdArg(1, arg1, sizeof(arg1));
	GetCmdArg(2, arg2, sizeof(arg2));
	GetCmdArg(3, arg3, sizeof(arg3));
	
	new Float:origin[3];
	
	origin[0] = StringToFloat(arg1);
	origin[1] = StringToFloat(arg2);
	origin[2] = StringToFloat(arg3);
	
	for(new i = 1; i <= MaxClients; ++i)
	{
		if (IsClientInGame(i))
		{
			TeleportEntity(i, origin, NULL_VECTOR, NULL_VECTOR);
		}
	}
	
	return Plugin_Handled;
}
